version: "3.8"

services:
  api:
    build:
      context: .
    container_name: weather_api
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_container
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    env_file:
      - .env
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  postgres_data:
